baseURL = "https://thedevdash.com/"

languageCode = "en-us"
title = "DevDash Documentation"
theme = "hugo-theme-learn"

[params]
  googleAnalyticsUserID= "UA-46898153-8"

[outputs]
  home = [ "HTML", "RSS", "JSON"]

[blackfriday]
  hrefTargetBlank = true

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Github"
identifier = "gs"
url = "https://github.com/Phantas0s/devdash"
weight = 10

[[menu.shortcuts]]
name = "<i class='fab fa-discord'></i> Discord Community"
identifier = "ds"
url = "https://discord.gg/aFHJ7ec"
weight = 20

[[menu.shortcuts]]
name = "<i class='fab fa-envelope-open'></i> Newsletter"
identifier = "ns"
url = "/newsletter/"
weight = 30
