baseURL = "https://thedevdash.com/"

languageCode = "en-us"
title = "DevDash Documentation"
theme = "hugo-theme-learn"

[outputs]
  home = [ "HTML", "RSS", "JSON"]

[blackfriday]
  hrefTargetBlank = true

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Github"
identifier = "gs"
url = "https://github.com/Phantas0s/devdash"
weight = 10
