baseURL = "https://thedevdash.com/"

languageCode = "en-us"
title = "DevDash Documentation"
theme = "hugo-theme-learn"

[params]
  themeVariant = "green"

[outputs]
  home = [ "HTML", "RSS", "JSON"]

[blackfriday]
  hrefTargetBlank = true

[[menu.shortcuts]] 
name = "<i class='fab fa-github'></i> Github"
identifier = "ds"
url = "https://github.com/Phantas0s/devdash"
weight = 10

[[menu.shortcuts]] 
name = "<i class='fab fa-envelope-open'></i> Newsletter"
identifier = "ns"
url = "/newsletter/"
weight = 20
